name: Unzipper

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Descomprimir
        run: |
          unzip data.zip
          rm data.zip
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Descomprimir archivo"
          git push
